version: "3"

services:

  db:
    image: postgres
    restart: on-failure
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../.env
    
  app:
    build: ../
    restart: on-failure
    volumes:
      - ..:/workspace:cached